/**
 * @file tokenizer.h
 * @brief This file contains the logic for tokenizing the Pith language.
 * It defines the token types, the tokenizer state, and the main tokenizing function.
 */

#ifndef PITH_TOKENIZER_H
#define PITH_TOKENIZER_H

// Enum for all possible token types generated by the tokenizer
typedef enum {
    TOKEN_EOF,
    TOKEN_KEYWORD,
    TOKEN_IDENTIFIER,
    TOKEN_STRING,
    TOKEN_NUMBER,
    TOKEN_FLOAT_LITERAL,
    TOKEN_LPAREN,    // (
    TOKEN_RPAREN,    // )
    TOKEN_LBRACKET,  // [
    TOKEN_RBRACKET,  // ]
    TOKEN_LBRACE,    // {
    TOKEN_RBRACE,    // }
    TOKEN_COLON,     // :
    TOKEN_COMMA,     // ,
    TOKEN_SEMICOLON, // ;
    TOKEN_DOT,       // .
    TOKEN_PLUS,      // +
    TOKEN_MINUS,     // -
    TOKEN_STAR,      // *
    TOKEN_SLASH,     // /
    TOKEN_PERCENT,   // %
    TOKEN_CARET,     // ^
    TOKEN_ASSIGN,    // =
    TOKEN_GT,        // >
    TOKEN_LT,        // <
    TOKEN_GTE,       // >=
    TOKEN_LTE,       // <=
    TOKEN_EQ,        // ==
    TOKEN_NEQ,       // !=
    TOKEN_BANG,      // !
    TOKEN_NEWLINE,
    TOKEN_INDENT,
    TOKEN_DEDENT,
    TOKEN_IMPORT
} TokenType;

// The structure for a single token
typedef struct {
    TokenType type;
    char *value;
    int line_num;
} Token;

// Structure to hold the tokenizer's state
typedef struct {
    Token *tokens;
    int token_count;
    int token_capacity;
} TokenizerState;

// The main function to tokenize a source string, now taking a state pointer
void tokenize(const char *source, TokenizerState *state);

#endif //PITH_TOKENIZER_H
